apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  labels:
    app: mongo
  name: db
  selfLink: /api/v1/namespaces/blue-seal-project/services/db
spec:
  ports:
  - name: 27017-tcp
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongo
    deploymentconfig: db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: null
  generation: 1
  labels:
    app: mongo
  name: db
  selfLink: /apis/apps.openshift.io/v1/namespaces/blue-seal-project/deploymentconfigs/db
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    app: mongo
    deploymentconfig: db
  strategy:
    type: Recreate
    recreateParams: 
      post:
          failurePolicy: Ignore
          execNewPod:
            command: [ "mongo", "--eval", "printjson(rs.initiate());printjson(cfg.members[0].host =spec.podName:27017);printjson(rs.reconfig(cfg, {force:true}))" ]
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        app: mongo
        deploymentconfig: db
    spec:
      containers:
      - image: bluewhalecr.azurecr.io/mongo_custom:latest
        imagePullPolicy: Always
        name: db
        ports:
        - containerPort: 27017
          protocol: TCP
        resources: 
          requests:
            cpu: 100Mi
            memory: 243Mi
          limits:
            cpu: 300Mi
            memory: 750Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/db
          name: db-volume-2
        - mountPath: /data/configdb
          name: db-volume-1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db-volume-2
        persistentVolumeClaim:
          claimName: mongodb-claim2
      - name: db-volume-1
        persistentVolumeClaim:
          claimName: mongodb-claim
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - db
      from:
        kind: ImageStreamTag
        name: db:latest
        namespace: blue-seal-project
    type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
