apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "limits-default" 
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "3" 
        memory: "1Gi" 
      min:
        cpu: "2" 
        memory: "500Mi" 
    - type: "Container"
      max:
        cpu: "3"
        memory: "1Gi" 
      min:
        cpu: "2"
        memory: "200Mi" 
