---
# A Team SVC hellodemo yaml - TzahiA
# This SVC will create a service for the hellodemo App
# Added the Loadbalancer for connecting to the outside
apiVersion: v1
kind: Service
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: hellodemo
    app.kubernetes.io/component: hellodemo
    app.kubernetes.io/instance: hellodemo
  name: hellodemo
  namespace: hello-demo
spec:
  clusterIP: 172.30.166.156
  ports:
  - name: 3000-tcp
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    deploymentconfig: hellodemo
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
