---
# A Team Demo Deployment v1.0 - TzahiA
# This is the default Resource quota per project
#
apiVersion: v1
kind: ResourceQuota
metadata:
  name: rq-default
spec:
  hard:
    # Make sure you set the requests/cpu and requests/mem on the Deployment config before
    requests.cpu: "30" 
    requests.memory: "40Gi"
    pods: "10"
    resourcequotas: "1"
    services.loadbalancers: "5"
    requests.storage: "100Gi"
